CREATE TABLE CLIENTS (
    Client_ID NUMBER PRIMARY KEY,
    Nom VARCHAR2(50) NOT NULL,
    Prenom VARCHAR2(50),
    Adresse VARCHAR2(100),
    Telephone VARCHAR2(15)
);

-- Table PRODUIT
CREATE TABLE PRODUIT (
    Produit_ID NUMBER PRIMARY KEY,
    Nom_Produit VARCHAR2(50) NOT NULL,
    Prix NUMBER(10, 2) NOT NULL
);

-- Table COMMANDES
CREATE TABLE COMMANDES (
    Commande_ID NUMBER PRIMARY KEY,
    Client_ID NUMBER,
    Date_Commande DATE,
    FOREIGN KEY (Client_ID) REFERENCES CLIENTS(Client_ID)
);

-- Table DETAILS_COMMANDE
CREATE TABLE DETAILS_COMMANDE (
    Details_ID NUMBER PRIMARY KEY,
    Commande_ID NUMBER,
    Produit_ID NUMBER,
    Quantite NUMBER,
    FOREIGN KEY (Commande_ID) REFERENCES COMMANDES(Commande_ID),
    FOREIGN KEY (Produit_ID) REFERENCES PRODUIT(Produit_ID)
);
ALTER TABLE PRODUIT ADD Catégorie VARCHAR2(20);
ALTER TABLE COMMANDES ADD Date_de_commande DATE DEFAULT SYSDATE;